GET http://localhost:5000/api
authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjIiLCJpYXQiOjE1OTE3NDUxNTEsImV4cCI6MTU5MTc0NTc1MX0.yGYc8jdhTvfV0GYPiCUoCPUoAglp-HdsCdPKTkNqQT4

###

POST http://localhost:5000/api HTTP/1.1
authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjIiLCJpYXQiOjE1OTE3NDUxNTEsImV4cCI6MTU5MTc0NTc1MX0.yGYc8jdhTvfV0GYPiCUoCPUoAglp-HdsCdPKTkNqQT4
content-type: application/json

{
    "name": "Netflix",
    "location": "Los Gatos, CA",
    "image_url": "https://assets.brand.microsites.netflix.io/assets/fbd0c908-b388-11e7-9274-06c476b5c346_cm_800w.png?v=34",
    "careers_url": "https://careers.google.com/jobs/"
}

###
PUT http://localhost:5000/api/4 HTTP/1.1
content-type: application/json

{
    "id": 4,
    "name": "test11",
    "location": "test11",
    "image_url": "test11",
    "careers_url": "test11"
}

###

DELETE http://localhost:5000/api/4 HTTP/1.1
content-type: application/json

###

POST http://localhost:5000/api/signup HTTP/1.1
content-type: application/json

{
    "username": "user26",
    "password": "password26"
}

###

POST http://localhost:5000/api/login HTTP/1.1
content-type: application/json

{
    "username": "user2",
    "password": "password2"
}

###

GET http://localhost:5000/api/home HTTP/1.1
authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjIiLCJpYXQiOjE2MDk1NjE2ODcsImV4cCI6MTYwOTU2MjI4N30.qVxNbQhXujmUKVWv-E78zuRYZI2aMkGUdrqbG9Pk-QM
content-type: application/json

{
    "id": 2
}
