GET http://localhost:5000/api

###

POST http://localhost:5000/api HTTP/1.1
content-type: application/json

{
    "name": "Netflix",
    "location": "Los Gatos, CA",
    "image_url": "https://assets.brand.microsites.netflix.io/assets/fbd0c908-b388-11e7-9274-06c476b5c346_cm_800w.png?v=34",
    "careers_url": "https://careers.google.com/jobs/"
}

###
PUT http://localhost:5000/api/4 HTTP/1.1
content-type: application/json

{
    "id": 4,
    "name": "test11",
    "location": "test11",
    "image_url": "test11",
    "careers_url": "test11"
}

###

DELETE http://localhost:5000/api/4 HTTP/1.1
content-type: application/json

###

